/*
 * Copyright (c) 2025, OpenSavvy and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package opensavvy.gitlab.ci

import opensavvy.gitlab.ci.yaml.Yaml
import opensavvy.gitlab.ci.yaml.yaml
import opensavvy.gitlab.ci.yaml.yamlMap

/**
 * Declares which environment this job interacts with.
 *
 * To declare the environment, see [Job.environment].
 */
@GitLabCiDsl
class Environment internal constructor() : YamlExport {
	internal var name: String? = null
	private var url: String? = null
	private var onStop: Job? = null
	private var action: EnvironmentAction = EnvironmentAction.Start
	private var tier: EnvironmentTier? = null
	private var autoStopIn: String? = null
	private var kubernetes: Kubernetes? = null

	/**
	 * Declares the name of the environment, as it will be displayed in the GitLab UI.
	 *
	 * ```kotlin
	 * val deploy-qa by job {
	 *     script {
	 *         // …
	 *     }
	 *
	 *     environment {
	 *         name("qa")
	 *         url("https://qa.your.app/dashboard")
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://docs.gitlab.com/ci/yaml/#environmentname)
	 */
	@GitLabCiDsl
	fun name(name: String) {
		this.name = name
	}

	/**
	 * Declares the URL on which the deployed environment is available.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * val deploy-qa by job {
	 *     script {
	 *         // …
	 *     }
	 *
	 *     environment {
	 *         name("qa")
	 *         url("https://qa.your.app/dashboard")
	 *     }
	 * }
	 * ```
	 *
	 * ### Example: dynamic URL
	 *
	 * The URL can be generated by the job itself by combining this feature with [Artifacts.dotenv]:
	 * ```kotlin
	 * val deploy-qa by job {
	 *     script {
	 *         shell("QA_URL=$(./generate-url) >>qa.env")
	 *     }
	 *
	 *     artifacts {
	 *         dotenv("qa.env")
	 *     }
	 *
	 *     environment {
	 *         name("qa")
	 *         url($$"$QA_URL")
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://docs.gitlab.com/ci/yaml/#environmenturl)
	 */
	@GitLabCiDsl
	fun url(url: String) {
		this.url = url
	}

	/**
	 * Specifies a [stopJob] that will be executed once the environment should be stopped.
	 *
	 * The stop job should have the same configuration but without a declared [url].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * val stopQa by job {
	 *     script {
	 *         // …
	 *     }
	 *
	 *     environment {
	 *         name("qa")
	 *     }
	 * }
	 *
	 * val deployQa by job {
	 *     script {
	 *         // …
	 *     }
	 *
	 *     environment {
	 *         name("qa")
	 *         url("https://qa.your.app/dashboard")
	 *         onStop(stopQa)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://docs.gitlab.com/ci/yaml/#environmenton_stop)
	 */
	@GitLabCiDsl
	fun stopJob(stopJob: Job) {
		this.onStop = stopJob
	}

	/**
	 * Specify how this job interacts with the environment. See [EnvironmentAction].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * val verifyQa by job {
	 *     script {
	 *         // …
	 *     }
	 *
	 *     environment {
	 *         name("qa")
	 *         action(EnvironmentAction.Verify)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://docs.gitlab.com/ci/yaml/#environmentaction)
	 */
	@GitLabCiDsl
	fun action(action: EnvironmentAction) {
		this.action = action
	}

	/**
	 * Declares which tier this job deploys.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * val verifyQa by job {
	 *     script {
	 *         // …
	 *     }
	 *
	 *     environment {
	 *         name("qa")
	 *         tier(EnvironmentTier.Testing)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://docs.gitlab.com/ci/yaml/#environmentaction)
	 */
	@GitLabCiDsl
	fun tier(tier: EnvironmentTier) {
		this.tier = tier
	}

	/**
	 * Declares the lifetime of the environment. When the environment expires, GitLab automatically stops it.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * val reviewApp by job {
	 *     script {
	 *         // …
	 *     }
	 *
	 *     environment {
	 *         name("review/\$CI_COMMIT_REF_SLUG")
	 *         autoStopIn("1 day")
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://docs.gitlab.com/ci/yaml/#environmentauto_stop_in)
	 */
	@GitLabCiDsl
	fun autoStopIn(duration: String) {
		this.autoStopIn = duration
	}

	/**
	 * Configures the dashboard for Kubernetes and GitLab-managed Kubernetes resources for this environment.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * val deploy by job {
	 *     script {
	 *         // …
	 *     }
	 *
	 *     environment {
	 *         name("production")
	 *         kubernetes {
	 *             agent("path/to/agent/project:agent-name")
	 *             dashboardNamespace("my-namespace")
	 *             dashboardFluxResourcePath("helm.toolkit.fluxcd.io/v2/namespaces/flux-system/helmreleases/helm-release-resource")
	 *         }
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://docs.gitlab.com/ci/yaml/#environmentkubernetes)
	 */
	@GitLabCiDsl
	fun kubernetes(configuration: Kubernetes.() -> Unit) {
		this.kubernetes = Kubernetes().apply(configuration)
	}

	override fun toYaml(): Yaml {
		val data = HashMap<Yaml, Yaml>()

		if (name != null)
			data[yaml("name")] = yaml(name)

		if (url != null && action != EnvironmentAction.Stop)
			data[yaml("url")] = yaml(url)

		data[yaml("action")] = yaml(action.name.lowercase())

		if (tier != null)
			data[yaml("deployment_tier")] = yaml(tier!!.name.lowercase())

		if (autoStopIn != null)
			data[yaml("auto_stop_in")] = yaml(autoStopIn)

		if (kubernetes != null)
			data[yaml("kubernetes")] = kubernetes!!.toYaml()

		return yamlMap(data)
	}

	enum class EnvironmentAction {
		/**
		 * 	Default value. Indicates that the job starts the environment. The deployment is created after the job starts.
		 */
		Start,

		/**
		 * 	Indicates that the job is only preparing the environment. It does not trigger deployments. [Read more about preparing environments](https://docs.gitlab.com/ci/environments/#access-an-environment-for-preparation-or-verification-purposes).
		 */
		Prepare,

		/**
		 * 	Indicates that the job stops an environment. [Read more about stopping an environment](https://docs.gitlab.com/ci/environments/#access-an-environment-for-preparation-or-verification-purposes).
		 */
		Stop,

		/**
		 * 	Indicates that the job is only verifying the environment. It does not trigger deployments. [Read more about verifying environments](https://docs.gitlab.com/ci/environments/#access-an-environment-for-preparation-or-verification-purposes).
		 */
		Verify,

		/**
		 * 	Indicates that the job is only accessing the environment. It does not trigger deployments. [Read more about accessing environments](https://docs.gitlab.com/ci/environments/#access-an-environment-for-preparation-or-verification-purposes).
		 */
		Access,
	}

	enum class EnvironmentTier {
		Production,
		Staging,
		Testing,
		Development,
		Other,
	}

	/**
	 * Configures the dashboard for Kubernetes and GitLab-managed Kubernetes resources for an [Environment].
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://docs.gitlab.com/ci/yaml/#environmentkubernetes)
	 */
	@GitLabCiDsl
	class Kubernetes internal constructor() : YamlExport {
		private var agent: String? = null
		private var dashboardNamespace: String? = null
		private var dashboardFluxResourcePath: String? = null
		private var managedResourcesEnabled: Boolean? = null

		/**
		 * Declares the GitLab agent for Kubernetes used by this environment.
		 *
		 * The format is `path/to/agent/project:agent-name`. If the agent is connected to the project running the
		 * pipeline, use `$CI_PROJECT_PATH:agent-name`.
		 */
		@GitLabCiDsl
		fun agent(agent: String) {
			this.agent = agent
		}

		/**
		 * Declares the Kubernetes namespace where the environment is deployed.
		 *
		 * Must be set together with [agent]. Deprecated by GitLab in favor of [dashboardFluxResourcePath].
		 */
		@GitLabCiDsl
		fun dashboardNamespace(namespace: String) {
			this.dashboardNamespace = namespace
		}

		/**
		 * Declares the full path to the Flux resource (such as a `HelmRelease`) for this environment.
		 *
		 * Must be set together with [agent] and [dashboardNamespace]. Deprecated.
		 */
		@GitLabCiDsl
		fun dashboardFluxResourcePath(path: String) {
			this.dashboardFluxResourcePath = path
		}

		/**
		 * Enables or disables the GitLab-managed Kubernetes resources for this environment.
		 */
		@GitLabCiDsl
		fun managedResourcesEnabled(enabled: Boolean) {
			this.managedResourcesEnabled = enabled
		}

		override fun toYaml(): Yaml = yamlMap {
			addNotNull("agent", agent)

			if (managedResourcesEnabled != null) {
				add("managed_resources", yamlMap { addNotNull("enabled", managedResourcesEnabled) })
			}

			if (dashboardNamespace != null || dashboardFluxResourcePath != null) {
				add(
					"dashboard",
					yamlMap {
						addNotNull("namespace", dashboardNamespace)
						addNotNull("flux_resource_path", dashboardFluxResourcePath)
					}
				)
			}
		}
	}
}
