stages:
  - build
  - test
  - deploy

variables:
  jdk_image: "openjdk:17-bullseye"

include:
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/gradle.gitlab-ci.yml
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/version.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

test:
  image: $jdk_image
  stage: test
  extends: [ .os.gradle ]
  needs: [ ]

  script:
    - "./gradlew test"

  artifacts:
    when: always
    paths:
      - build/reports/tests/test
    reports:
      junit: build/test-results/test/TEST-*.xml

  interruptible: true

publish:
  image: $jdk_image
  stage: deploy
  extends: [ .os.gradle ]
  needs: [ test ]

  script:
    - "./gradlew publishAllPublicationsToGitLabRepository"

  rules:
    - if: $CI_PIPELINE_REF_NAME == $CI_DEFAULT_BRANCH
  interruptible: false
