stages:
  - build
  - test
  - deploy

variables:
  jdk_image: "openjdk:17-bullseye"

include:
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/gradle.gitlab-ci.yml
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/version.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

test:
  image: $jdk_image
  stage: test
  extends: [ .os.gradle ]
  needs: [ ]

  script:
    - "./gradlew test"

  artifacts:
    when: always
    paths:
      - build/reports/tests/test
    reports:
      junit: build/test-results/test/TEST-*.xml

  interruptible: true

dokka:
  image: $jdk_image
  stage: build
  extends: [ .os.gradle ]
  needs: [ ]

  script:
    - ./gradlew dokkaHtml
    - mkdir -p docs
    - mv build/dokka/html/* docs

  artifacts:
    paths:
      - docs
    expose_as: 'Documentation'

  environment:
    name: review/$CI_COMMIT_REF_SLUG/documentation
    url: https://$CI_PROJECT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/docs/index.html
    deployment_tier: development
    auto_stop_in: 1 week

  interruptible: true

publish:
  image: $jdk_image
  stage: deploy
  extends: [ .os.gradle ]
  needs: [ test ]

  script:
    - "./gradlew publishAllPublicationsToGitLabRepository"

  rules:
    - if: $CI_PIPELINE_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
  interruptible: false
