# List of dependencies of the project

[versions]
prepared = "1.5.2"       # https://gitlab.com/opensavvy/groundwork/prepared/-/releases

[plugins]

[libraries]
prepared = { module = "dev.opensavvy.prepared:runner-kotest", version.ref = "prepared" }
prepared-files = { module = "dev.opensavvy.prepared:compat-filesystem", version.ref = "prepared" }

[bundles]
